/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.uis.libreria.villaclau.vista;

import co.edu.uis.libreria.villaclau.controlador.Controlador_cliente;
import co.edu.uis.libreria.villaclau.controlador.Controlador_pantallas;
import co.edu.uis.libreria.villaclau.modelo.Cliente;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author Nataly
 */
public class VCliente extends javax.swing.JFrame {

    /**
     * Creates new form VCliente
     */
    public VCliente() {
        initComponents();
        cargar_modelo_Cliente();
        Controlador_cliente.cargar_clientes(tbl_clientes, modelo_Cliente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbl_Cliente = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_Id_cliente = new javax.swing.JTextField();
        txt_Nombre = new javax.swing.JTextField();
        txt_Direccion = new javax.swing.JTextField();
        txt_Telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_clientes = new javax.swing.JTable();
        btn_Registrar = new javax.swing.JButton();
        btn_Eliminar = new javax.swing.JButton();
        btn_Actualizar = new javax.swing.JButton();
        btb_Listar = new javax.swing.JButton();
        btn_VolveralMenu = new javax.swing.JButton();
        txt_buscar = new javax.swing.JTextField();
        btn_buscar_id = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Clientes");

        jLabel3.setText("Id_Cliente");

        jLabel4.setText("Nombre");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        txt_Id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Id_clienteActionPerformed(evt);
            }
        });

        txt_Direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DireccionActionPerformed(evt);
            }
        });

        tbl_clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_clientes);

        btn_Registrar.setText("Registrar");
        btn_Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RegistrarActionPerformed(evt);
            }
        });

        btn_Eliminar.setText("Eliminar");
        btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarActionPerformed(evt);
            }
        });

        btn_Actualizar.setText("Actualizar");
        btn_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ActualizarActionPerformed(evt);
            }
        });

        btb_Listar.setText("Listar");
        btb_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btb_ListarActionPerformed(evt);
            }
        });

        btn_VolveralMenu.setText("Volver al Menu");
        btn_VolveralMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolveralMenuActionPerformed(evt);
            }
        });

        btn_buscar_id.setText("Buscar ID");
        btn_buscar_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tbl_ClienteLayout = new javax.swing.GroupLayout(tbl_Cliente);
        tbl_Cliente.setLayout(tbl_ClienteLayout);
        tbl_ClienteLayout.setHorizontalGroup(
            tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbl_ClienteLayout.createSequentialGroup()
                .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(btn_VolveralMenu))
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tbl_ClienteLayout.createSequentialGroup()
                                .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Actualizar)
                                    .addComponent(btn_Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_Eliminar)
                                    .addComponent(btb_Listar)))
                            .addGroup(tbl_ClienteLayout.createSequentialGroup()
                                .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_Id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel2))
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btn_buscar_id)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );
        tbl_ClienteLayout.setVerticalGroup(
            tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tbl_ClienteLayout.createSequentialGroup()
                .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscar_id)
                        .addGap(1, 1, 1)
                        .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Eliminar)
                            .addComponent(btn_Registrar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(tbl_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Actualizar)
                            .addComponent(btb_Listar))
                        .addGap(18, 18, 18)
                        .addComponent(btn_VolveralMenu))
                    .addGroup(tbl_ClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_Cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DireccionActionPerformed

    private void txt_Id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Id_clienteActionPerformed
        
    }//GEN-LAST:event_txt_Id_clienteActionPerformed

    private void btn_RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RegistrarActionPerformed
        int id_Cliente= Integer.parseInt(txt_Id_cliente.getText());
        String nombre= txt_Nombre.getText();
        String direccion= txt_Direccion.getText();
        String telefono= txt_Telefono.getText();
        Cliente cl =new Cliente(id_Cliente,nombre, direccion, telefono);
        Controlador_cliente.guardar_cliente(cl);
        limpiar_espacios();
        Controlador_cliente.cargar_clientes(tbl_clientes, modelo_Cliente);
    }//GEN-LAST:event_btn_RegistrarActionPerformed

    private void btn_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ActualizarActionPerformed
        int id_Cliente= Integer.parseInt(txt_Id_cliente.getText());
        String nombre= txt_Nombre.getText();
        String direccion= txt_Direccion.getText();
        String telefono= txt_Telefono.getText();
        Cliente cl =new Cliente(id_Cliente,nombre, direccion, telefono);
        Controlador_cliente.actualizar_cliente(cl);
        limpiar_espacios();
        Controlador_cliente.cargar_clientes(tbl_clientes, modelo_Cliente);
        txt_Id_cliente.setEnabled(true);
    }//GEN-LAST:event_btn_ActualizarActionPerformed

    private void cargar_editar_cliente(){
        int fila_select= tbl_clientes.getSelectedRow();
        if(fila_select >= 0){
            txt_Id_cliente.setText((tbl_clientes.getValueAt(fila_select, 0).toString()));
            txt_Nombre.setText((tbl_clientes.getValueAt(fila_select, 1).toString()));
            txt_Direccion.setText((tbl_clientes.getValueAt(fila_select, 2).toString()));
            txt_Telefono.setText((tbl_clientes.getValueAt(fila_select, 3).toString()));
        }
      txt_Id_cliente.setEnabled(false);
    }
    
    
    private void btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarActionPerformed
        int id= Integer.parseInt( JOptionPane.showInputDialog(null,"Digite el ID del cliente que quiere eliminar"));
        Controlador_cliente.eliminar_cliente(id, tbl_clientes, modelo_Cliente);
        Controlador_cliente.cargar_clientes(tbl_clientes, modelo_Cliente);
        
    }//GEN-LAST:event_btn_EliminarActionPerformed

    private void btb_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btb_ListarActionPerformed
        Controlador_cliente.cargar_clientes(tbl_clientes, modelo_Cliente);
    }//GEN-LAST:event_btb_ListarActionPerformed

    private void btn_VolveralMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolveralMenuActionPerformed
        Controlador_pantallas.abrir_pantalla_menu();
        Controlador_pantallas.cerrar_pantalla_Cliente();
    }//GEN-LAST:event_btn_VolveralMenuActionPerformed

    private void tbl_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientesMouseClicked
        cargar_editar_cliente();
    }//GEN-LAST:event_tbl_clientesMouseClicked

    private void btn_buscar_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_idActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(txt_buscar.getText()) ;
        Controlador_cliente.cargar_clientes_id(id, tbl_clientes, modelo_Cliente);
    }//GEN-LAST:event_btn_buscar_idActionPerformed
    public void limpiar_espacios(){
        txt_Id_cliente.setText("");
        txt_Nombre.setText("");
        txt_Direccion.setText("");
        txt_Telefono.setText("");
    }
    
    DefaultTableModel modelo_Cliente= new DefaultTableModel();
    
    private void cargar_modelo_Cliente(){
        modelo_Cliente.addColumn("Id_Cliente");
        modelo_Cliente.addColumn("Nombre");
        modelo_Cliente.addColumn("Direccion");
        modelo_Cliente.addColumn("Telefono");
        
        tbl_clientes.setModel(modelo_Cliente);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btb_Listar;
    private javax.swing.JButton btn_Actualizar;
    private javax.swing.JButton btn_Eliminar;
    private javax.swing.JButton btn_Registrar;
    private javax.swing.JButton btn_VolveralMenu;
    private javax.swing.JButton btn_buscar_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel tbl_Cliente;
    private javax.swing.JTable tbl_clientes;
    private javax.swing.JTextField txt_Direccion;
    private javax.swing.JTextField txt_Id_cliente;
    private javax.swing.JTextField txt_Nombre;
    private javax.swing.JTextField txt_Telefono;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
